nguage: c
sudo: required
perl:
  - '5.10'
  - '5.12'
  - '5.14'
  - '5.16'
  - '5.18'
  - '5.20'
  - '5.22'
  - '5.24'
addons:
   postgresql: "9.6"
env:
  - COVERAGE=1 RELEASE_TESTING=1 DB_TESTING=1
install:
  - sudo apt-get install postgres-server-dev
  - make install
script:
  - make installcheck
