nguage: c
sudo: required
addons:
   postgresql: "9.6"
env:
  - COVERAGE=1 RELEASE_TESTING=1 DB_TESTING=1
install:
  - sudo apt-get install postgresql-server-dev-9.6
  - sudo make install
script:
  - make installcheck
after_failure:
  - cat /home/travis/build/adjust/pg-telemetry/regression.diffs
